### ISSUE TITLE
Boot failure caused by using both display ports on Rocket Lake with integrated GPUs

### ISSUE THREAD

**Issue by bflanagin** [pop-os/linux#107]
There is a continuing issue with intel based motherboards and their display ports which causes the system to hang when setting the frame buffer.

## Steps to reproduce:
* Plug in multiple displays to an Intel machine that uses the integrated GPU.
* Boot the system.

So far no boot options have been found to fix the issue.

## Work around:
Unplug one of the displays until the system starts to boot.

**Comment by jacobgkau** [comment]
Potentially-related upstream issue: https://gitlab.freedesktop.org/drm/intel/-/issues/4150

**Comment by bflanagin** [comment]
Link I found earlier about the issue. 
I've also tried all the suggested fixes from earlier issues with the same symptoms. None of which worked.

https://superuser.com/questions/1694659/connecting-two-monitors-at-boot-causes-linux-kernel-to-hang-when-enabling-kms

**Comment by leviport** [comment]
Brock tested a 10th gen (i3-10100) in mira-b1, and it boots fine with 2 displays.

**Comment by leviport** [comment]
Fixed by https://github.com/pop-os/linux/pull/123
