### ISSUE TITLE
tag source for kernel updates pushed to PopOS

### ISSUE THREAD

**Issue by qhaas** [pop-os/linux#112]
I'm having to apply some tweaks / patches to various in-tree kernel modules [using dkms](https://www.collabora.com/news-and-blog/blog/2021/05/05/quick-hack-patching-kernel-module-using-dkms/) and given there is no guarantee that the source for a given kernel module will be the same as those [tagged upstream](https://github.com/torvalds/linux/tags) after Ubuntu and later PopOS makes modifications, it would be useful to have the PopOS kernel releases tagged in GitHub after stable packages built from said codebase are pushed to the PopOS apt repos.

Also, the head of master's codename in `debian.master/changelog` is jammy, which implies 22.04 baseline, would be useful to have a separate branch for focal (20.04) given we have one for bionic (18.04).  It appears a `master_focal` once existed, but has been deleted.

Ubuntu [provides tags](https://kernel.ubuntu.com/git/ubuntu-stable/ubuntu-stable-focal.git/) similar to what is requested above for PopOS.

**Comment by jackpot51** [comment]
All kernels for 20.04 and later are derived from the `master` branch now. It is always rebased on tags you can get from the upstream kernel repository, currently 5.15.11 - https://github.com/pop-os/linux/commit/fb6ad5cb3b6745e7bffc5fe19b130f3594375634

**Comment by qhaas** [comment]
Thanks, so unlike Ubuntu, PopOS uses the same kernel for 21.10 and 20.04 and the head of `master` always tracks the latest stable release to PoPOS 20.04 / 21.10.  That would explain why I couldn't find an equivalent Ubuntu tagged release from their focal repo, especially if PopOS is not basing the releases on the Ubuntu fork, but instead are going directly to the [original tagged release](https://github.com/torvalds/linux/tags).  Sounds like most of PopOS' kernel fork changes are mainly related to packaging and build scripts?  If so, I should be free to assume no significant code changes from upstream.
