### ISSUE TITLE
Upstream update: 5.4.0-29.33

### ISSUE THREAD

**Issue by jackpot51** [pop-os/linux#13]
master_focal has been rebased in https://github.com/pop-os/linux/commit/ff6e79e1d746058e726fa3c221a5f2aeb4d4fee2

**Comment by leviport** [comment]
This looks good to me. I tested it on gaze14 (1660ti), darp5 (open firmware & EC), thelio-major-r2 (rx580), thelio-r2 (integrated AMD), and thelio-b2 (GTX 1070). All seemed well.
