### ISSUE TITLE
"Disk does not meet the minimum requirement" is pointlessly hidden in hover

### ISSUE THREAD

**Issue by matkoniecz** [pop-os/linux#189]
following https://support.system76.com/articles/install-in-vm/ results in mysterious 

![screen03](https://user-images.githubusercontent.com/899988/199935203-93e19d29-a951-4309-997d-ef193ef22a9f.png)

hovering over it results in displaying "Disk does not meet the minimum requirement"

Why this message is not just shown? There is plenty of space for it.

(I hope that is the correct repo, in https://github.com/pop-os/website/issues/73 I reported broken tutorial but maybe also detecting dynamically allocated disk size is broken here?)

**Comment by leviport** [comment]
It sounds to me like this isn't a kernel bug, but rather a UX concern with Gnome Boxes. This should probably be reported to the Boxes team if that is the case.

**Comment by matkoniecz** [comment]
where it can be reported?

**Comment by leviport** [comment]
Ah, I think I understand now. Your screenshot was from Pop's graphical installer. I thought the screenshot was taken from the VM host program. I'll reopen, rename, and move this issue to the correct repository for you.
