### ISSUE TITLE
Regression when connected to external displays through dock

### ISSUE THREAD

**Issue by thomas-zimmerman** [pop-os/linux#235]
Report from HP/Dev One : 

```
If I shut down and restart the laptop with the dock plugged into the laptop via usb-c all 
displays work.

However, if the laptop goes to sleep, or displays turn off, or if I put laptop into suspend 
mode, the screens do not come back. I can still use the mouse and the laptop 
“remembers” the screen locations (can move the mouse cursor onto the blank external 
monitors).

Only way to fix is to shut down and restart the laptop.
```

Verified that 6.1 and 6.2 do not work with display connected via HP Thunderbolt 120W G2 Dock -- direct connection between Dev One and monitor continues to function.

**Comment by boenshao** [comment]
Same issue of #226. Still waiting for a fix.

**Comment by AndreaRicchi** [comment]
Same on Lenovo ThinkPad T14s Gen 2i. USB-C display output not working in any conditions

**Comment by leviport** [comment]
Let's track this in https://github.com/pop-os/linux/issues/226 if it is the same bug. If I'm mistaken, then we can reopen this one.
