### ISSUE TITLE
Intermittent Wi-Fi connectivity issues on boot (mt7921e driver)

### ISSUE THREAD

**Issue by jacobktm** [pop-os/linux#254]
**Distribution (run `cat /etc/os-release`):**
 
 NAME="Pop!_OS"
VERSION="22.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 22.04 LTS"
VERSION_ID="22.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=jammy
UBUNTU_CODENAME=jammy
LOGO=distributor-logo-pop-os
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

The issue is related to the mt7921e Wi-Fi driver, which is part of the kernel.

**Issue/Bug Description:**

Sporadically, during system boot, Wi-Fi is unavailable, and no networks can be detected or connected to. This issue does not occur on every boot, but it happens occasionally. A reboot or system suspension resolves the problem, and Wi-Fi becomes available again.

**Steps to reproduce (if you know):**

1. Boot the system.
2. Occasionally, the Wi-Fi is not available during the boot process.

**Expected behavior:**

Wi-Fi should be consistently available and functional during every system boot without requiring a reboot or suspension to resolve the issue.

**Other Notes:**

I have seen this behavior on several systems with a MediaTek wireless adapter, including pang12, mira-r3, and major-r4. The Wi-Fi driver in question is the mt7921e driver, which is part of the kernel. I have also seen this issue in both Pop!_OS 22.04 and Ubuntu 22.04 with the Pop PPA and kernel installed.

**Comment by 0dinD** [comment]
I don't think the MediaTek drivers are part of the kernel itself, but rather, they are part of the separately distributed `linux-firmware` package: https://git.kernel.org/pub/scm/linux/kernel/git/firmware/linux-firmware.git/tree/LICENCE.mediatek

---

I think this issue describes the same problem as mentioned here: https://github.com/pop-os/pop/issues/530#issuecomment-1614732241

At least two other people have reported issues with the MediaTek MT7921/MT7922 Wi-Fi devices in that issue, and other than Wi-Fi sometimes being unavailable on boot, there seems to be a related issue where the laptop also hangs during shutdown whenever the Wi-Fi is unavailable. If you are having only the Wi-Fi issue, but not the "hang during shutdown" issue, maybe the MT7921E that you have behaves slightly differently than the MT7921 and MT7922.

Either way, MediaTek have submitted several patches for these 3 Wi-Fi devices during the past months, so I'm hoping that pop-os/linux-firmware#35 will have fixed the issue. I think all that's left before we can try the `20230629` version of `linux-firmware` is a release here: https://github.com/pop-os/repo-release

**Comment by pktiuk** [comment]
> EDIT: The new version of linux-firmware is now available in the Pop!_OS APT repository, let's try it and hope that it fixes the issue.

I think this issue can be closed for now. In my case I did not have this problem since the update (this is not a very long time, but still). How about you @jacobktm  ?

In case if this is not fixed it could be reopened
