### ISSUE TITLE
HP Dev One resolution options are only 1080p on 6.4.6 kernel

### ISSUE THREAD

**Issue by ahoneybun** [pop-os/linux#269]
After upgrading to the 6.4.6 kernel only 1080p is available on the Dev One. Works correctly if booting to oldkern which is 6.2.6.

![Screenshot from 2023-08-05 23-57-07](https://github.com/pop-os/linux/assets/4884946/2dccfcb2-6a89-4ed1-adfd-6563c220c10b)

xrandr output:

```
Screen 0: minimum 320 x 200, current 3072 x 1728, maximum 16384 x 16384
eDP connected primary 3072x1728+0+0 (normal left inverted right x axis y axis) 309mm x 174mm
   1920x1080     60.01*+
HDMI-A-0 disconnected (normal left inverted right x axis y axis)
DisplayPort-0 disconnected (normal left inverted right x axis y axis)
DisplayPort-1 disconnected (normal left inverted right x axis y axis)
```

**Comment by leviport** [comment]
>Works correctly if booting to oldkern which is 6.2.6.

Please describe the behavior you expect in greater detail. Many displays only display the native resolution, which for Dev One is 1920x1080.

**Comment by leviport** [comment]
From an IRL discussion, I've been notified that the expected behavior is to be able to select lower (non-native) resolutions.

**Comment by ahoneybun** [comment]
I also confirmed that the options are there if you are on Wayland and not there for Xorg.

**Comment by leviport** [comment]
Appears to be resolved by https://github.com/pop-os/linux/pull/273

**Comment by leviport** [comment]
Fixed by https://github.com/pop-os/linux/pull/276, which will release soon.
