### ISSUE TITLE
Bug: People can install Microsoft Edge

### ISSUE THREAD

**Issue by grian32** [pop-os/linux#30]
This is a bug because installing Microsoft Edge on linux is commits treason in the linux kernel.
Commiting treason in linux immediatly bricks one's computer.

**Comment by ids1024** [comment]
Prosecuting treason against the Linux kernel is outside our jurisdiction. One may attempt to report the issue upstream. Good luck with that.

(In other news, we've also ruled wiping hard drives with repetitions on the string `VIM` when a user installs Emacs.)

Closing.
