### ISSUE TITLE
Headset/headphone combo prompt stopped appearing on darp10 and darp10-b

### ISSUE THREAD

**Issue by leviport** [pop-os/linux#330]
I think we might have dropped https://github.com/pop-os/linux/pull/310 in an update.

**Comment by XV-02** [comment]
Looking at our current master file for the patches, the line we have in our production kernel is missing. 

Interestingly, the master branch for Torvald has the following
`SND_PCI_QUIRK(0x1558, 0xa763, "Clevo V54x_6x_TU", ALC256_FIXUP_SYSTEM76_MIC_NO_PRESENCE),`
as opposed to 
`SND_PCI_QUIRK(0x1558, 0xa763, "Clevo V5[46]0TU", ALC256_FIXUP_SYSTEM76_MIC_NO_PRESENCE),`
As a result of this [commit](https://github.com/torvalds/linux/commit/e1c6db864599be341cd3bcc041540383215ce05e)
