### ISSUE TITLE
Latest kernel update broke networking

### ISSUE THREAD

**Issue by Dlm5008** [pop-os/linux#43]
I am required to use bcmwl-kernel-source to enable networking on a 2011 MacBook Pro.  After the latest kernel upgrade to 5.11 the networking was broken and failed to load.  When attempting to uninstall the package: bcmwl-kernel-source it would not properly uninstall and would not install.  The following error occurred:  failed to install bcmwl-kernel-source

Error while installing package:
installed bcmwl-kernel-source
package post-installation script
subprocess returned error exit
status 10

I was able to revert back to kernel 5.8 to regain the networking.

**Comment by jackpot51** [comment]
This will be fixed soon, see https://github.com/pop-os/pop/issues/1603

**Comment by jackpot51** [comment]
> Please ensure you have bcmwl-kernel-source 6.30.223.271+bdcom-0ubuntu8pop0 or later installed. This should fix issues with compiling the driver on linux 5.11
