### ISSUE TITLE
Bluetooth on Thelio r1 not working after upgrading to kernel 5.11

### ISSUE THREAD

**Issue by joseluisrojas21** [pop-os/linux#44]
Pop OS! 20.10

Kernel:
Linux pop-os 5.11.0-7612-generic #13~1617215757~20.10~97a8d1a-Ubuntu SMP Thu Apr 1 21:09:17 UTC 2 x86_64 x86_64 x86_64 GNU/Linux

Wireless card:
Wireless-AC 9260

Linux Firmware info:
Package: linux-firmware
Version: 1.196+system76~1617376058~20.10~eb867cb
Priority: optional
Section: misc
Maintainer: Ubuntu Kernel Team <kernel-team@lists.ubuntu.com>
Installed-Size: 687 MB
Provides: atmel-firmware
Conflicts: atmel-firmware
Breaks: linux-firmware-raspi2 (<= 1.20190819-0ubuntu2), linux-firmware-snapdragon (<= 1.2-0ubuntu1)
Replaces: atmel-firmware, linux-firmware-snapdragon (<= 1.2-0ubuntu1), linux-restricted-common
Download-Size: 159 MB
APT-Manual-Installed: no
APT-Sources: http://ppa.launchpad.net/system76/pop/ubuntu groovy/main amd64 Packages
Description: Firmware for Linux kernel drivers
 This package provides firmware used by Linux kernel drivers.

**Comment by bflanagin** [comment]
@joseluisrojas21: I've got two bluetooth devices installed on my Thelio r1 running 5.11.  Can you give us the output from bluetoothctl?:

'bluetoothctl show > bt_device.txt`

`bluetoothctl devices > bt_devices.txt` 

The second command may not show anything but it will give us a good starting place to work through the issue.

**Comment by joseluisrojas21** [comment]
I am going to close this since an update fixed the issue yesterday.
