### ISSUE TITLE
CLEVO NH5X and possibly NH7X series touchpad freezes during install and after install

### ISSUE THREAD

**Issue by allen-munsch** [pop-os/linux#57]
CLEVO NH5X and possibly NH7X series

Looks like there is a possible hacky work around.

see:

- https://bugzilla.kernel.org/show_bug.cgi?id=213579

Can someone at system76 reach out to Clevo to see if they can fix this issue?

I tried re-compiling the kernel/modules with the fix, but got about as far as `sudo make install && sudo reboot -h` and had it stall on boot up.

Not sure if system76 sells the NH58HPQ, but that is the version I was using.

Just figured I'd let y'all know

**Comment by jackpot51** [comment]
We fixed this in the firmware we use on our TGL-H units. Ask your hardware vendor for support

**Comment by allen-munsch** [comment]
@jackpot51 happen to know which repo that fix is in?
