### ISSUE TITLE
5.15.5 on intel 6th gen CPU: long startup, long reboot, NO powerdown or suspend unless Vt-d is disabled.

### ISSUE THREAD

**Issue by spxak1** [pop-os/linux#86]
This is on 21.04 (system details at the end).

Lot's of edits on this sorry, but I put things together as it goes.

### Slow after POST
Once the EFI stub is read, it takes a while to load the kernel. Normally this starts right away, it takes a good 8-10 seconds from EFI stub: Loaded initrd from command line option to actually load it and get started the boot process. With 5.13 this was instant.

### Slow boot
Like a timeout, but actually these are the two **oops**.

### Slow reboot 
From ```sudo reboot``` to POST screen it takes under 10 seconds in 5.13, but over 27 seconds in 5.15.5. The time added is between the OS finishing and the laptop restarting (before POST). Which links to the next item

### Here's the weird part: The laptop does not shutdown.
The process appears to be completed as usual (some output, I'll check later for details), the screen goes off, power button goes off, but keyboard backlight stays on, keyboard LEDs stay on and the fans stay on. I need to keep the power button for 4 seconds to turn off.

Same behaviour when suspending to RAM. Obviously there is no waking up from it as the power button is irresponsive, opening the lid won't change anything and only thing left to do is hold the power button for a hard power off and then restart as normal.

**All of the above are resolved once VT-d is disabled in the bios.**  So something in this kernel doesn't agree with my laptop's (or CPU) VT-d. I will keep it disabled and keep testing (although I will need it back on for my VM's). 

## Info
~~~
NAME="Pop!_OS"
VERSION="21.04"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 21.04"
VERSION_ID="21.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=hirsute
UBUNTU_CODENAME=hirsute
LOGO=distributor-logo-pop-os
~~~

~~~
Linux weywot 5.15.5-76051505-generic #202111250933~1638201579~21.04~09f1aa7-Ubuntu SMP Tue Nov 30 02: x86_64 x86_64 x86_64 GNU/Linux
~~~

**Comment by spxak1** [comment]
Update:

Removing ```acpi-call-dkms```, and rebooting makes the **oops** stop. No more **oops**. Re-installing ```acpi-call-dkms``` after keeps it that way, so I guess the **oops** problem is gone.

But powering down is still the biggest issue.

Finally,  it takes a good 8-10 seconds from ```EFI stub: Loaded initrd from command line option``` to  actually load it and get started the boot process. With 5.13 this was instant.

**Comment by spxak1** [comment]
## More testing on the rebooting/booting/poweroff/suspend issue.

I have done a separate installation of 21.10 beta to test what is coming my way soon. 
Steps:

* Enable VT-d in bios
* Clean install 21.10 beta (.2 iso)
* 5.15.0 out of the box works fine. That is, booting is as fast as expected, ditto with rebooting. The system powers down properly and suspends and resumes as expected.
* 5.15.5 installed via apt-get.
* Same behaviour as with 21.04. From EFI stub to loading intramfs takes 12 seconds, reboot extremely slow to POST (i.e before loading the EFI stub), system will not power off or suspend but rather turn power LED off but keep keyboard LEDs + fans running (to no end).
* Reboot, disable VT-d.
* System behaves as expected (as with 5.15.0). All issues resolved.
* Reboot, enable VT-d.
* 5.15.6 **mainline** installed. 
* Same behaviour as 5.15.5. No improvement.
* Reboot, disable VT-d.
* System behaves as expected (as with 5.15.0). All issues resolved.
* Reboot, enable VT-d.
* Remove 5.15.6 **mainline**, install 5.15.6 **xanmod**, reboot to **xanmod**
* System behaves as expected, all issues resolved. No need to disable VT-d. 

So evidently with the same mainline kernel, xanmod does not cause this issue, while the vanilla mainline does.

I hope this helps.

Thanks.
*

**Comment by spxak1** [comment]
Some more reports of boot/reboot/poweroff/suspend issues here:

* https://www.reddit.com/r/pop_os/comments/r7p1k8/reboot_started_fully_shutting_down_and_then/
* https://www.reddit.com/r/pop_os/comments/r7wa6y/so_ive_run_from_every_distro_because_of_this/

This is narrowed down to 6th Gen intel CPUs.

**Comment by fouadzouraibi** [comment]
pop!_OS 21.04, after kernel 5.15 update, no suspend nor reboot or shutdown. Disable VT-d in bios seems to fix issue.

**Comment by BaronKrause** [comment]
I can confirm. Laptop with Intel 6th Gen CPU, same issues after Kernel 5.15.. Resolved after disabling VT-d.

**Comment by holdforther** [comment]
Same issue here, hotfixed by disabling VT-d in BIOS
Laptop: Thinkpad T460, i5 6300u
OS: Pop_OS! 21.04, kernel 5.15.5

**Comment by abrighton** [comment]
Same problem with Lenovo Thinkpad P70, OS: Pop_OS! 21.04, kernel 5.15.5.
Reverting to the previous 5.13 kernel is also a temporary workaround.

**Comment by spxak1** [comment]
I can confirm this is a problem with Haswell CPU's too. The issue is focused on graphics.

Here's a video of the issue: https://www.youtube.com/watch?v=XprqYp9iMtc

Solution is either to use a kernel older than 5.15.5 (5.15.4 and older works fine). Or to disable VT-d in the bios.

Thank you.

**Comment by polhaghverdian** [comment]
I have the same problem. 6th gen Xeon laptop.

Lenovo ThinkPad P50
Intel® Xeon(R) CPU E3-1505M v5 @ 2.80GHz × 8 
NVIDIA Corporation GM107GLM [Quadro M2000M] / Quadro M2000M/PCIe/SSE2

**Comment by spxak1** [comment]
Jut to confirm, 5.15.8 has **not** fixed the issue.

Also to confirm that Xanmod, Manjaro and Fedora on the same kernel work fine.

**Comment by jackpot51** [comment]
I diffed the configs for the Arch kernel and the Pop kernel of the same version. It looks like our kernel has `CONFIG_INTEL_IOMMU_DEFAULT_ON` set to `y` while it is unset for the Arch kernel. I wonder if booting with `intel_iommu=off` as a kernel parameter works around the issues. This would mimic the config of the Arch kernel.

**Comment by polhaghverdian** [comment]
> 

That is basically disabling VT-d if am not mistaken. That is one solution, but not viable for those who need it.

**Comment by spxak1** [comment]
> I diffed the configs for the Arch kernel and the Pop kernel of the same version. It looks like our kernel has `CONFIG_INTEL_IOMMU_DEFAULT_ON` set to `y` while it is unset for the Arch kernel. I wonder if booting with `intel_iommu=off` as a kernel parameter works around the issues. This would mimic the config of the Arch kernel.

@jackpot51 I'm testing it now. In the mean time, please note Xanmod kernel doesn't have that issue in any version of 5.15. 

Thanks.

**Comment by moeffju** [comment]
I have the same issue with a Thinkpad T460. Previous Pop!OS has been working just fine including sleep and resume, after upgrading to 21.10, sleep/resume does not work anymore as described in this thread.

CPU is i5-6300U with Intel HD 520 Graphics.
I've disabled VT-d for now.

**Comment by pbui** [comment]
@spxak1 Could you try `intel_iommu=igfx_off` instead of `intel_iommu=off`?  That would keep iommu on but not for the igpu.  That is what I needed to stop the flickering issue (on 8th gen Intel).

I would guess that `CONFIG_INTEL_IOMMU_DEFAULT_ON=y` is equivalent to `intel_iommu=on`, while `intel_iommu=off` is equivalent to `CONFIG_INTEL_IOMMU=n`... which is not exactly the same as what xanmod and archlinux is doing.   

By unsetting `CONFIG_INTEL_IOMMU_DEFAULT_ON`, it may allow for certain kernel systems to selectively enable the iommu for whatever it believes is appropriate rather than force enabling it by default across the board.

Either way, it seems as though unsetting CONFIG_INTEL_IOMMU_DEFAULT_ON would be a good fix it resolves this issue.  Users can always force it on with `intel_iommu=on`.

BTW, here are some bug reports related to the iommu setting and why archlinux has disabled it:

https://bugs.archlinux.org/task/55629
https://bugs.archlinux.org/task/65362
https://bugzilla.kernel.org/show_bug.cgi?id=197029

**Comment by spxak1** [comment]
> @spxak1 Could you try `intel_iommu=igfx_off` instead of `intel_iommu=off`? That would keep iommu on but not for the igpu. That is what I needed to stop the flickering issue (on 8th gen Intel).
> 
> I would guess that `CONFIG_INTEL_IOMMU_DEFAULT_ON=y` is equivalent to `intel_iommu=on`, while `intel_iommu=off` is equivalent to `CONFIG_INTEL_IOMMU=n`... which is not exactly the same as what xanmod and archlinux is doing.
> 
> By unsetting `CONFIG_INTEL_IOMMU_DEFAULT_ON`, it may allow for certain kernel systems to selectively enable the iommu for whatever it believes is appropriate rather than force enabling it by default across the board.
> 
> Either way, it seems as though unsetting CONFIG_INTEL_IOMMU_DEFAULT_ON would be a good fix it resolves this issue. Users can always force it on with `intel_iommu=on`.
> 
> BTW, here are some bug reports related to the iommu setting and why archlinux has disabled it:
> 
> https://bugs.archlinux.org/task/55629 https://bugs.archlinux.org/task/65362 https://bugzilla.kernel.org/show_bug.cgi?id=197029

Thanks. I'll play with it later when I have time and report back. I need to do some reading on IOMMU. I am not even sure how much for that VT-d it affects, or how much I and my peers **actually** use in their VM's. 

Thanks again.

P.S. I see there is a pull request for 5.15.10 that will settle this. Thanks @jackpot51
