### ISSUE TITLE
WiFi+Bluetooth module not added into the kernel from Ubuntu kernel

### ISSUE THREAD

**Issue by VenomIND** [pop-os/linux#9]
Issue: My WiFi + Bluetooth modules are added into the Ubuntu 20.04 5.4 kernel .. but none of those working in pop OS. 

Expected solution: Please add those module from default Ubuntu 5.4 lts kernel. rtw88(8723DE)

Device info : 
Os: Pop-OS 20.04 beta (Upgrade 19.10)
Model- HP-da0326tu
Wireless module- Realtek RTL8723DE .
Processor: Intel i3-7100U
RAM-8 GB

**Comment by jackpot51** [comment]
We have this module in /lib/modules/5.4.0-7624-generic/kernel/drivers/net/wireless/realtek/rtw88/rtw88.ko

Can you confirm you have that file?

**Comment by VenomIND** [comment]
@jackpot51 Thanks for your efforts and quick response.. I really appreciate it .. I upgraded from 19.10 which doesn't work but after downloading the new ISO of 20.04 it worked after reinstall... I really like Pop-OS .. although I can't afford system 76 device yet (because of student) but it's in my wishlist .. ☺️☺️ again thank you.

**Comment by jackpot51** [comment]
Glad to hear a fresh install worked better! We're still working on beta upgrade issues, thanks for reporting!

**Comment by VenomIND** [comment]
Yes.. @jackpot51 I have seen your interview on LearnLinuxTV YouTube channel.. it was amazing.. I'm from India and System76 laptops are not shipping to India currently I guess.. so can I expect availability in upcoming 2-3 years ?☺️☺️
