### ISSUE TITLE
Suspend broken on Dell XSP 15 7590

### ISSUE THREAD

**Issue by RafalSkolasinski** [pop-os/linux#95]
**How did you upgrade to 21.10? (Fresh install / Upgrade)**

 
Upgrade from 21.04.

 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

Not sure which one would that be.

**Issue/Bug Description:**

After upgrade the suspend feature stopped to work. Laptop either restarts on wake or becomes totally unresponsive. 

**Steps to reproduce (if you know):**

1. Get Dell XPS 15 7590
2. Upgrade from 21.04 to 21.10
3. Try to suspend.

**Expected behavior:**

It suspends and wakes up like before.

**Other Notes:**

I did initially suspect it was because of forcing cgroups v1 as per https://github.com/pop-os/beta/issues/289 my other issue but reverting that change didn't fix the suspend.

I tried live usb with Kubuntu 21.10 and it did work fine. I may try live USB of PopOS 21.10 (I believe you have one?) to verify.

Happy to provide additional information. I planned to reinstall my machine back to 21.04 but decided to postpone by a day or two in case you'd like to get some more information about the problem or have some advice.

**Comment by RafalSkolasinski** [comment]
Still issue on Live CD of 21.10. Tested Kubuntu 21.10 and no issue there.

**Comment by aindriu80** [comment]
I fixed my issue by reinstalling Pop OS

**Comment by RafalSkolasinski** [comment]
That would indicate that there is a patch in repositories, just didn't make it yet to the live cd?

**Comment by RafalSkolasinski** [comment]
After upgrading to 21.10 now from 21.04 the issue seem to be now resolved. Update that fixed had probably not make it yet into the live cd.
