### ISSUE TITLE
Chromium based browsers flickering on kernel 5.15

### ISSUE THREAD

**Issue by JulioSordi** [pop-os/linux#97]
Distribution 

 Pop OS! 20.04 LTS
 
Related Application and/or Package Version

```
linux-image-5.15.5-76051505-generic:
  Instalado: 5.15.5-76051505.202111250933~1638201579~20.04~09f1aa7
  Candidato: 5.15.5-76051505.202111250933~1638201579~20.04~09f1aa7
  Tabela de versão:
 *** 5.15.5-76051505.202111250933~1638201579~20.04~09f1aa7 1001
       1001 http://ppa.launchpad.net/system76/pop/ubuntu focal/main amd64 Packages
        100 /var/lib/dpkg/status

brave-browser:
  Instalado: 1.32.113
  Candidato: 1.32.113
  Tabela de versão:
 *** 1.32.113 500
        500 https://brave-browser-apt-release.s3.brave.com stable/main amd64 Packages
        100 /var/lib/dpkg/status
     1.32.106 500
        500 https://brave-browser-apt-release.s3.brave.com stable/main amd64 Packages
     1.31.91 500
        500 https://brave-browser-apt-release.s3.brave.com stable/main amd64 Packages
     1.31.88 500
        500 https://brave-browser-apt-release.s3.brave.com stable/main amd64 Packages
     1.31.87 500
        500 https://brave-browser-apt-release.s3.brave.com stable/main amd64 Packages
     1.30.89 500
        500 https://brave-browser-apt-release.s3.brave.com stable/main amd64 Packages
     1.30.87 500
        500 https://brave-browser-apt-release.s3.brave.com stable/main amd64 Packages
     1.30.86 500
        500 https://brave-browser-apt-release.s3.brave.com stable/main amd64 Packages

microsoft-edge-stable:
  Instalado: 96.0.1054.34-1
  Candidato: 96.0.1054.34-1
  Tabela de versão:
 *** 96.0.1054.34-1 100
        100 /var/lib/dpkg/status
```

Issue/Bug Description:

The pages randomly flicker as if they were flashing
the issue occurs in the following situations:

- While normally browsing the web
- while typing on a post
- while scrolling pages
- when i leave the mouse still for a few seconds
- when i open a link
- when i select text

The following applications display this issue:

- Brave browser
- Microsoft Edge

Occurs in the following kernel:

- Kernel 5.15-generic

Steps to reproduce

- Open a Chromium based browser (Preferably Brave or Edge)
- browse the web as normal
- Google something and open a link
- select some text
- type on some kind of post
- scroll through the pages
- leave the mouse still for a few seconds

Expected behavior:

The page will not flicker

Other Notes:

sometimes the whole page flickers, sometimes only the bottom
does not occur in full screen videos
i wasn't able to record or screenshot the flickering unfortunately
the issue might be present in Chromium or other derivatives that i haven't tested (Vivaldi, Opera, Ungoogled Chromium, Chrome).

**Comment by bradleeedmondson** [comment]
I believe I am seeing this issue too, with a PowerColor 6800 XT running PopOS 21.04 in a custom rig.

I see random flickering on both monitors with kernel 5.15, while booting with backup kernel 5.13 has no issue. Flickering affects whole display (including desktop background), not just specific apps/windows, but seems like it happens more frequently when using Chrome (I have full Google Chrome 96.0.4664.93 -- don't judge). The GPU has worked flawlessly up until a few days ago when I first booted with 5.15.





Showing the flickering issue: 5.15.5-76051505-generic:

```
$ inxi -Fz
System:    Kernel: 5.15.5-76051505-generic x86_64 bits: 64 Desktop: GNOME 3.38.4 
           Distro: Pop!_OS 21.04 
Machine:   Type: Desktop Mobo: ASRock model: B450 Pro4 serial: <filter> 
           UEFI: American Megatrends v: P5.00 date: 05/10/2021 
CPU:       Info: 8-Core model: AMD Ryzen 7 5800X bits: 64 type: MCP L2 cache: 4 MiB 
           Speed: 2870 MHz min/max: 2200/3800 MHz Core speeds (MHz): 1: 2870 2: 2870 
           3: 2871 4: 2860 5: 2850 6: 2220 7: 2198 8: 2696 
Graphics:  Device-1: AMD Navi 21 [Radeon RX 6800/6800 XT / 6900 XT] driver: amdgpu 
           v: kernel 
           Display: server: X.Org 1.20.11 driver: loaded: amdgpu,ati 
           unloaded: fbdev,modesetting,radeon,vesa resolution: 1: 3840x2160~60Hz 
           2: 3840x2160~60Hz 
           OpenGL: renderer: AMD Radeon RX 6800 XT (SIENNA_CICHLID DRM 3.42.0 
           5.15.5-76051505-generic LLVM 12.0.0) 
           v: 4.6 Mesa 21.2.2 
Audio:     Device-1: AMD driver: snd_hda_intel 
           Device-2: AMD Starship/Matisse HD Audio driver: snd_hda_intel 
           Device-3: Microdia Webcam Vitade AF type: USB driver: snd-usb-audio,uvcvideo 
           Device-4: C-Media Audio Adapter (Unitek Y-247A) type: USB 
           driver: cmedia_hs100b,snd-usb-audio,usbhid 
           Sound Server: ALSA v: k5.15.5-76051505-generic 
Network:   Device-1: Realtek RTL8111/8168/8411 PCI Express Gigabit Ethernet driver: r8169 
           IF: enp9s0 state: up speed: 1000 Mbps duplex: full mac: <filter> 
Drives:    Local Storage: total: 931.51 GiB used: 660.34 GiB (70.9%) 
           ID-1: /dev/nvme0n1 vendor: Samsung model: SSD 980 1TB size: 931.51 GiB 
Partition: ID-1: / size: 19.56 GiB used: 10.88 GiB (55.6%) fs: ext4 dev: /dev/dm-1 
           ID-2: /boot/efi size: 1.95 GiB used: 239.4 MiB (12.0%) fs: vfat 
           dev: /dev/nvme0n1p1 
           ID-3: /home size: 859.81 GiB used: 649.23 GiB (75.5%) fs: ext4 dev: /dev/dm-3 
Swap:      ID-1: swap-1 type: partition size: 35 GiB used: 0 KiB (0.0%) dev: /dev/dm-2 
Sensors:   Message: No sensors data was found. Is sensors configured? 
Info:      Processes: 290 Uptime: 8m Memory: 31.28 GiB used: 2.07 GiB (6.6%) Shell: Bash 
           inxi: 3.3.01
```




Not showing the flickering issue: 5.13.0-7620-generic:


```
$ inxi -Fz

System:    Kernel: 5.13.0-7620-generic x86_64 bits: 64 Desktop: GNOME 3.38.4 Distro: Pop!_OS 21.04 
Machine:   Type: Desktop Mobo: ASRock model: B450 Pro4 serial: <filter> UEFI: American Megatrends v: P5.00 date: 05/10/2021 
CPU:       Info: 8-Core model: AMD Ryzen 7 5800X bits: 64 type: MCP L2 cache: 4 MiB 
           Speed: 2194 MHz min/max: 2200/3800 MHz Core speeds (MHz): 1: 2194 2: 2195 3: 2196 4: 2190 5: 2189 6: 2195 7: 2195 
           8: 2195 
Graphics:  Device-1: Advanced Micro Devices [AMD/ATI] Navi 21 [Radeon RX 6800/6800 XT / 6900 XT] driver: amdgpu v: kernel 
           Display: server: X.Org 1.20.11 driver: loaded: amdgpu,ati unloaded: fbdev,modesetting,radeon,vesa resolution: 
           1: 3840x2160~60Hz 2: 3840x2160~60Hz 
           OpenGL: renderer: AMD Radeon RX 6800 XT (SIENNA_CICHLID DRM 3.41.0 5.13.0-7620-generic LLVM 12.0.0) 
           v: 4.6 Mesa 21.2.2 
Audio:     Device-1: Advanced Micro Devices [AMD/ATI] driver: snd_hda_intel 
           Device-2: Advanced Micro Devices [AMD] Starship/Matisse HD Audio driver: snd_hda_intel 
           Device-3: Microdia Webcam Vitade AF type: USB driver: snd-usb-audio,uvcvideo 
           Device-4: C-Media Audio Adapter (Unitek Y-247A) type: USB driver: hid-generic,snd-usb-audio,usbhid 
           Sound Server: ALSA v: k5.13.0-7620-generic 
Network:   Device-1: Realtek RTL8111/8168/8411 PCI Express Gigabit Ethernet driver: r8169 
           IF: enp9s0 state: up speed: 1000 Mbps duplex: full mac: <filter> 
Drives:    Local Storage: total: 931.51 GiB used: 660.33 GiB (70.9%) 
           ID-1: /dev/nvme0n1 vendor: Samsung model: SSD 980 1TB size: 931.51 GiB 
Partition: ID-1: / size: 19.56 GiB used: 10.88 GiB (55.6%) fs: ext4 dev: /dev/dm-1 
           ID-2: /boot/efi size: 1.95 GiB used: 239.4 MiB (12.0%) fs: vfat dev: /dev/nvme0n1p1 
           ID-3: /home size: 859.81 GiB used: 649.21 GiB (75.5%) fs: ext4 dev: /dev/dm-3 
Swap:      ID-1: swap-1 type: partition size: 35 GiB used: 0 KiB (0.0%) dev: /dev/dm-2 
Sensors:   Message: No sensors data was found. Is sensors configured? 
Info:      Processes: 296 Uptime: 1m Memory: 31.28 GiB used: 1.46 GiB (4.7%) Shell: Bash inxi: 3.3.01 
```






I have two custom .deb repos, but neither affect kernel:
http://dl.google.com/linux/chrome/deb/
http://repo.zabbix.com/zabbix/5.0/ubuntu/

**Comment by Eduardo06sp** [comment]
Also happens on my bone stock lemp9. However I am not using Chrome, I use FireFox.
Version: Pop!_OS 21.04
Kernel: Linux 5.15.5-76051505-generic x86_64

I opened a support ticket through their portal, I apologize if this is unnecessary

**Comment by JulioSordi** [comment]
> Also happens on my bone stock lemp9. However I am not using Chrome, I use FireFox. Version: Pop!_OS 21.04 Kernel: Linux 5.15.5-76051505-generic x86_64
> 
> I opened a support ticket through their portal, I apologize if this comment is unnecessary

I hope someone has an explanation for why this is happening, it seems i'm not the only one who's affected, i wonder why Pop 20.04 LTS upgraded the kernel so soon, did Ubuntu upgrade the kernel too?

**Comment by JorisVanEijden** [comment]
Attaching dmesg output from a 5.13 (no flickering) and a 5.15 (flickering) boot.
[dmesg_5_13.txt](https://github.com/pop-os/linux/files/7674035/dmesg_5_13.txt)
[dmesg_5_15.txt](https://github.com/pop-os/linux/files/7674036/dmesg_5_15.txt)

**Comment by guyvdbroeck** [comment]
I have this issue on a fresh install lemp10 laptop.

**Comment by JulioSordi** [comment]
> I have this issue on a fresh install lemp10 laptop.

Please run inxi -F in the terminal and post the output here, the developers need as much info as you can provide.

Open terminal --> type inxi -F --> select the whole output then copy it with Ctrl Shift C --> start a new comment here, press Ctrl E to insert code then paste the terminal output.

**Comment by leviport** [comment]
@guyvdbroeck Please include the OS version you did a clean install with, as well as the packages you installed after installing the OS. If I can recreate this on my lemp10 it would be immensely helpful for troubleshooting.

**Comment by guyvdbroeck** [comment]
```
System:
  Host: voyager Kernel: 5.15.5-76051505-generic x86_64 bits: 64 
  Desktop: GNOME 3.38.4 Distro: Pop!_OS 21.04 
Machine:
  Type: Laptop System: System76 product: Lemur Pro v: lemp10 
  serial: <superuser required> 
  Mobo: System76 model: Lemur Pro v: lemp10 serial: <superuser required> 
  UEFI: coreboot v: 2021-07-20_93c2809 date: 07/20/2021 
Battery:
  ID-1: BAT0 charge: 68.6 Wh condition: 76.2/73.9 Wh (103%) 
CPU:
  Info: Quad Core model: 11th Gen Intel Core i5-1135G7 bits: 64 type: MT MCP 
  L2 cache: 8 MiB 
  Speed: 1128 MHz min/max: 400/4200 MHz Core speeds (MHz): 1: 1128 2: 1235 
  3: 1003 4: 855 5: 1129 6: 1128 7: 1103 8: 1003 
Graphics:
  Device-1: Intel TigerLake GT2 [Iris Xe Graphics] driver: i915 v: kernel 
  Device-2: Chicony Chicony USB2.0 Camera type: USB driver: uvcvideo 
  Display: x11 server: X.Org 1.20.11 driver: loaded: modesetting 
  unloaded: fbdev,vesa resolution: 1920x1080~60Hz 
  OpenGL: renderer: Mesa Intel Xe Graphics (TGL GT2) v: 4.6 Mesa 21.2.2 
Audio:
  Device-1: Intel Tiger Lake-LP Smart Sound Audio driver: snd_hda_intel 
  Sound Server: ALSA v: k5.15.5-76051505-generic 
Network:
  Device-1: Intel Wi-Fi 6 AX201 driver: iwlwifi 
  IF: wlp0s20f3 state: up mac: 60:e3:2b:ae:10:5a 
Bluetooth:
  Device-1: Intel type: USB driver: btusb 
  Report: ID: hci0 state: up running bt-v: 3.0 address: 60:E3:2B:AE:10:5E 
Drives:
  Local Storage: total: 931.51 GiB used: 252.24 GiB (27.1%) 
  ID-1: /dev/nvme0n1 vendor: Western Digital model: WDS100T2B0C-00PXH0 
  size: 931.51 GiB 
Partition:
  ID-1: / size: 907.51 GiB used: 249.48 GiB (27.5%) fs: ext4 dev: /dev/dm-1 
  ID-2: /boot/efi size: 511 MiB used: 355.8 MiB (69.6%) fs: vfat 
  dev: /dev/nvme0n1p1 
Swap:
  ID-1: swap-1 type: partition size: 4 GiB used: 0 KiB (0.0%) dev: /dev/dm-2 
Sensors:
  System Temperatures: cpu: 57.0 C mobo: N/A 
  Fan Speeds (RPM): cpu: 0 
Info:
  Processes: 307 Uptime: 47m Memory: 23.33 GiB used: 3.61 GiB (15.5%) 
  Shell: Bash inxi: 3.3.01 
```

**Comment by pbui** [comment]
I was able to stop the flickering by adding `intel_iommu=igfx_off` to my kernel parameters.  This on an Intel only machine with an iGPU and has been effective for a week.

**Comment by JulioSordi** [comment]
> I was able to stop the flickering by adding `intel_iommu=igfx_off` to my kernel parameters. This on an Intel only machine with an iGPU and has been effective for a week.

Could you write a step by step instruction on how to modify kernel parameters? It would make things much easier for less experienced users, i often find the Arch Wiki too complicated, it never tells me how to do things and which commands i need to use.

**Comment by pbui** [comment]
You can use [kernelstub](https://github.com/pop-os/kernelstub) as follows:

```
sudo kernelstub -a intel_iommu=igfx_off
```

This will add that kernel parameter to `/etc/kernelstub/configuration` and to the `systemd-boot` entries in `/boot/efi/loader/entries/`.  For instance, after running that command above, the `/boot/efi/loader/entries/Pop_OS-current.conf` contains the following:

```
title Pop!_OS
linux /EFI/Pop_OS-241af729-d87a-45d0-9c76-a6db1260573a/vmlinuz.efi
initrd /EFI/Pop_OS-241af729-d87a-45d0-9c76-a6db1260573a/initrd.img
options root=UUID=241af729-d87a-45d0-9c76-a6db1260573a ro quiet loglevel=0 systemd.show_status=false splash intel_iommu=igfx_off
```

As you can see the kernel parameter we wanted to add is now on the `options` line.

If for whatever reason you want remove it (e.g. this problem is fixed properly, or this doesn't fix your issue), then you can do the following to remove the option:

```
sudo kernelstub -d intel_iommu=igfx_off
```

I hope that helps.  Note, this is not a proper fix... it is more of a workaround that I discovered from the [Intel-IOMMU kernel documentation](https://www.kernel.org/doc/Documentation/Intel-IOMMU.txt):

> If you encounter issues with graphics devices, you can try adding
option intel_iommu=igfx_off to turn off the integrated graphics engine.
If this fixes anything, please ensure you file a bug reporting the problem.

**Comment by bradleeedmondson** [comment]
Just to confirm, is anyone else seeing this on `amdgpu`? I've observed this with both Radeon 6800 XT and 6900 XT on a Ryzen 7 5800X box, and obviously any Intel driver-specific issues aren't applicable there (nor is the intel_iommu kernel setting).

**Comment by JorisVanEijden** [comment]
`intel_iommu=igfx_off` did not stop or reduce the issue for me.

**Comment by Steve-Z** [comment]
Same problem here, running Pop!_OS 20.04 on a Dell e7470. Seems to be a horizontal flickering of maximized windows. I have seen it on Firefox 95, Slack desktop client (4.22.0), and VS Code (1.63). It is perhaps triggered by scrolling vertically, but can persist for some seconds even when I stop scrolling.
```
sudo lshw -short
[sudo] password for steve: 
H/W path       Device     Class          Description
====================================================
                          system         Latitude E7470 (06DC)
/0                        bus            Motherboard
/0/0                      memory         64KiB BIOS
/0/41                     memory         64KiB L1 cache
/0/42                     memory         64KiB L1 cache
/0/43                     memory         512KiB L2 cache
/0/44                     memory         3MiB L3 cache
/0/45                     processor      Intel(R) Core(TM) i5-6300U CPU @ 2.40GH
/0/46                     memory         8GiB System Memory
/0/46/0                   memory         8GiB SODIMM DDR4 Synchronous 2133 MHz (
/0/46/1                   memory         DIMM [empty]
/0/100                    bridge         Xeon E3-1200 v5/E3-1500 v5/6th Gen Core
/0/100/2                  display        Skylake GT2 [HD Graphics 520]
/0/100/4                  generic        Xeon E3-1200 v5/E3-1500 v5/6th Gen Core
/0/100/14                 bus            Sunrise Point-LP USB 3.0 xHCI Controlle
/0/100/14/0    usb1       bus            xHCI Host Controller
/0/100/14/0/2             multimedia     Integrated_Webcam_HD
/0/100/14/0/7             generic        5880
/0/100/14/1    usb2       bus            xHCI Host Controller
/0/100/14.2               generic        Sunrise Point-LP Thermal subsystem
/0/100/16                 communication  Sunrise Point-LP CSME HECI #1
/0/100/16.3               communication  Sunrise Point-LP Active Management Tech
/0/100/17                 storage        82801 Mobile SATA Controller [RAID mode
/0/100/1c                 bridge         Sunrise Point-LP PCI Express Root Port 
/0/100/1c/0    wlp1s0     network        Wireless 8260
/0/100/1d                 bridge         Sunrise Point-LP PCI Express Root Port 
/0/100/1d/0               generic        RTS525A PCI Express Card Reader
/0/100/1f                 bridge         Sunrise Point-LP LPC Controller
/0/100/1f.2               memory         Memory controller
/0/100/1f.3               multimedia     Sunrise Point-LP HD Audio
/0/100/1f.4               bus            Sunrise Point-LP SMBus
/0/100/1f.6    enp0s31f6  network        Ethernet Connection I219-LM
/0/1                      system         PnP device PNP0c02
/0/2                      system         PnP device PNP0b00
/0/3                      generic        PnP device INT3f0d
/0/4                      input          PnP device PNP0303
/0/5                      generic        PnP device DLL06dc
/0/6                      printer        PnP device PNP0401
/0/7                      system         PnP device PNP0c02
/0/8                      system         PnP device PNP0c02
/0/9                      system         PnP device PNP0c02
/0/a                      system         PnP device PNP0c02
/0/b           scsi2      storage        
/0/b/0.0.0     /dev/sda   disk           512GB SK hynix SC311 S
/0/b/0.0.0/1   /dev/sda1  volume         511MiB Windows FAT volume
/0/b/0.0.0/2   /dev/sda2  volume         4095MiB Linux swap volume
/0/b/0.0.0/3   /dev/sda3  volume         472GiB EXT4 volume
/1                        power          DELL MC34Y51
uname --all
Linux pop-os 5.15.5-76051505-generic #202111250933~1638201579~20.04~09f1aa7-Ubuntu SMP Tue Nov 30 02: x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by JulioSordi** [comment]
Pop OS has just updated the kernel from 5.15.5 to 5.15.8, i haven't presenced any flickering in an uptime of 20 minutes, i'll keep everyone informed if i encounter any other issues.

**Comment by szul** [comment]
I have not had this issue recently either. :crossed_fingers:

**Comment by JorisVanEijden** [comment]
On 5.15.8 it is very much reduced but not completely gone here.
From avg 5 times a minute to about once every 5 minutes.

**Comment by Steve-Z** [comment]
> On 5.15.8 it is very much reduced but not completely gone here.
From avg 5 times a minute to about once every 5 minutes.

I'm doing a little better than that. Only a couple of times since I updated to 5.15.8. But not completely gone.

**Comment by JayAndCatchFire** [comment]
I am using a Lemur Pro 9 with a fresh install of Pop OS 21.10.  All updates have been applied. I'm also experiencing this issue. I don't think it's related to Chromium as I have Firefox installed. The issue happens infrequently, but it's still disconcerting. I think I've seen it happen while on a fullscreen terminal window. 

Sorry for what mostly amounts to a "me, too" post. I'm mostly just happy this is a known software issue and there's not a problem with my hardware. 😌

**Comment by JorisVanEijden** [comment]
I'm not sure if this ticket is even the right place for this issue. Is anyone here working on this?
It seem the application (I've only noticed it in Brave and Slack so far, my JetBrains IDEs seem unaffected) skips a frame in rendering so whatever is behind it is visible for a split second.
Since the update to 5.15.8 clobbered my 5.13 kernel I've resorted to making my desktop background a screenshot of my most frequently used windows. That way the effect is slightly less jarring :)

**Comment by JorisVanEijden** [comment]
Update: disabling hardware acceleration provides a workaround for me. 
In Brave: Settings->additional settings->System->Use hardware acceleration when available
In Slack: File->Preferences->Advanced->other options->Disable hardware acceleration

**Comment by JayAndCatchFire** [comment]
I just experienced it again in VSCode (Chromium-based...) while scrolling in the built-in terminal really fast.  First time I've experienced it in days.

**Comment by Steve-Z** [comment]
For me it was better, not gone but better, for a while, since the 5.15.8 update.

But in the past 1-2 days it has been bad, specifically Slack desktop client and VSCode. I have not rebooted since the update. Could that be having an effect.

**Comment by mohnishkodnani** [comment]
I experience it in the Brave Browser mostly, however, not limited to that alone. 
```
❯ inxi -Fz
System:
  Kernel: 5.15.8-76051508-generic x86_64 bits: 64 
  Desktop: GNOME 40.5 Distro: Pop!_OS 21.10 
Machine:
  Type: Laptop System: System76 product: Lemur Pro v: lemp9 
  serial: <filter> 
  Mobo: System76 model: Lemur Pro v: lemp9 serial: <filter> 
  UEFI: coreboot v: 2021-07-20_93c2809 date: 07/20/2021 
Battery:
  ID-1: BAT0 charge: 60.0 Wh (91.7%) 
  condition: 65.4/73.9 Wh (88.5%) 
CPU:
  Info: Quad Core model: Intel Core i5-10210U bits: 64 
  type: MT MCP cache: L2: 6 MiB 
  Speed: 1400 MHz min/max: 400/4200 MHz Core speeds (MHz): 
  1: 1400 2: 1300 3: 1300 4: 1312 5: 1406 6: 1563 7: 1535 
  8: 1583 
Graphics:
  Device-1: Intel CometLake-U GT2 [UHD Graphics] driver: i915 
  v: kernel 
  Device-2: Chicony Chicony USB2.0 Camera type: USB 
  driver: uvcvideo 
  Display: x11 server: X.Org 1.20.13 driver: loaded: modesetting 
  unloaded: fbdev,vesa resolution: 1920x1080~60Hz 
  OpenGL: renderer: N/A v: N/A 
Audio:
  Device-1: Intel Comet Lake PCH-LP cAVS driver: snd_hda_intel 
  Sound Server-1: ALSA v: k5.15.8-76051508-generic running: yes 
  Sound Server-2: PulseAudio v: 15.0 running: yes 
  Sound Server-3: PipeWire v: 0.3.32 running: yes 
Network:
  Device-1: Intel Comet Lake PCH-LP CNVi WiFi driver: iwlwifi 
  IF: wlp0s20f3 state: up mac: <filter> 
Bluetooth:
  Device-1: Intel Bluetooth 9460/9560 Jefferson Peak (JfP) 
  type: USB driver: btusb 
  Report: hciconfig ID: hci0 state: up address: <filter> 
  bt-v: 3.0 
Drives:
  Local Storage: total: 232.89 GiB used: 29.91 GiB (12.8%) 
  ID-1: /dev/nvme0n1 vendor: Western Digital 
  model: WDS250G2B0C-00PXH0 size: 232.89 GiB 
Partition:
  ID-1: / size: 219.86 GiB used: 27.22 GiB (12.4%) fs: ext4 
  dev: /dev/nvme0n1p3 
  ID-2: /boot/efi size: 511 MiB used: 255.6 MiB (50.0%) fs: vfat 
  dev: /dev/nvme0n1p1 
Swap:
  ID-1: swap-1 type: partition size: 4 GiB used: 0 KiB (0.0%) 
  dev: /dev/dm-0 
Sensors:
  System Temperatures: cpu: 68.0 C mobo: 53.0 C 
  Fan Speeds (RPM): cpu: 0 
Info:
  Processes: 307 Uptime: 6d 18h 14m Memory: 15.5 GiB 
  used: 5.17 GiB (33.4%) Shell: fish inxi: 3.3.06 
```
Last few messages for `dmesg`
```

```

**Comment by srett** [comment]
Has this been fixed? the radio silence for the last two months makes me assume so, but in case it hasn't: had similar issues after running Ubuntu 20.04 with kernel 5.15.x. I could solve the problem by updating mesa to the latest 22.0 build (which is still in RC phase as of now), or more specifically, just updating libgl1-mesa-dri was enough.
I fetched the prebuilt package from [here](https://launchpad.net/~ernstp/+archive/ubuntu/mesarc/+build/23224488), but not sure if this will install on Pop, dependency-wise. If you want to try installing this and apt tells you it needs to install and remove a dozen other packages, then don't do it.

**Comment by hexpunk** [comment]
Purely anecdotal, but I haven't noticed it happening to me in about a month.

**Comment by Steve-Z** [comment]
Same here. No problems for a while.

**Comment by leviport** [comment]
Good to hear. I'll close this issue for now. We can reopen if the bug returns.
